export type ComponentProp = {
  name: string;
  type: string;
  ru: string;
  en: string;
  default?: string | number | boolean;
  initial?: string | number | boolean;
  options?: readonly string[];
  control?: 'select' | 'text' | 'boolean' | 'number';
  demoOnly?: boolean;
  part?: string;
};

export type ComponentReference = {
  props: ComponentProp[];
  parts?: string[];
  kind?: 'hook';
  returns?: ComponentProp[];
};

const children: ComponentProp = {
  name: 'children',
  type: 'ReactNode',
  ru: 'Содержимое компонента.',
  en: 'Component content.',
};
const className: ComponentProp = {
  name: 'className',
  type: 'string',
  ru: 'Класс корневого элемента.',
  en: 'Class of the root element.',
};
const wrapperClassName: ComponentProp = {
  name: 'wrapperClassName',
  type: 'string',
  ru: 'Класс внешней обёртки.',
  en: 'Class of the outer wrapper.',
};
const textClassName: ComponentProp = {
  name: 'textClassName',
  type: 'string',
  ru: 'Класс текстовой части.',
  en: 'Class of the text part.',
};
const sizeSM: ComponentProp = {
  name: 'size',
  type: "'s' | 'm'",
  ru: 'Размер компонента.',
  en: 'Component size.',
  default: 'm',
  options: ['s', 'm'],
  control: 'select',
};
const sizeAll: ComponentProp = {
  name: 'size',
  type: "'xs' | 's' | 'm' | 'l'",
  ru: 'Размер компонента.',
  en: 'Component size.',
  default: 'm',
  options: ['xs', 's', 'm', 'l'],
  control: 'select',
};
const sizeSML: ComponentProp = {
  name: 'size',
  type: "'s' | 'm' | 'l'",
  ru: 'Размер компонента.',
  en: 'Component size.',
  default: 'm',
  options: ['s', 'm', 'l'],
  control: 'select',
};
const color: ComponentProp = {
  name: 'color',
  type: "'primary' | 'secondary' | 'success' | 'danger'",
  ru: 'Смысловой цвет.',
  en: 'Semantic color.',
  default: 'primary',
  options: ['primary', 'secondary', 'success', 'danger'],
  control: 'select',
};
const disabled: ComponentProp = {
  name: 'disabled',
  type: 'boolean',
  ru: 'Блокирует взаимодействие.',
  en: 'Disables interaction.',
  default: false,
  control: 'boolean',
};
const error: ComponentProp = {
  name: 'error',
  type: 'boolean',
  ru: 'Показывает состояние ошибки.',
  en: 'Shows the error state.',
  default: false,
  control: 'boolean',
};
const loading: ComponentProp = {
  name: 'loading',
  type: 'boolean',
  ru: 'Показывает процесс выполнения.',
  en: 'Shows a pending action.',
  default: false,
  control: 'boolean',
};
const checked: ComponentProp = {
  name: 'checked',
  type: 'boolean',
  ru: 'Текущее выбранное состояние.',
  en: 'Current selected state.',
  default: false,
  control: 'boolean',
};
const labelPlace: ComponentProp = {
  name: 'labelPlace',
  type: "'left' | 'right'",
  ru: 'Положение подписи относительно контрола.',
  en: 'Label position relative to the control.',
  default: 'right',
  options: ['left', 'right'],
  control: 'select',
};
const leftIcon: ComponentProp = {
  name: 'leftIcon',
  type: 'SvgType',
  ru: 'Иконка перед текстом; принимает SVG-компонент.',
  en: 'Icon before the text; accepts an SVG component.',
  options: ['none', 'check', 'search', 'user'],
  control: 'select',
  initial: 'none',
};
const rightIcon: ComponentProp = {
  name: 'rightIcon',
  type: 'SvgType',
  ru: 'Иконка после текста; принимает SVG-компонент.',
  en: 'Icon after the text; accepts an SVG component.',
  options: ['none', 'check', 'search', 'user'],
  control: 'select',
  initial: 'none',
};
const iconClasses: ComponentProp[] = [
  {
    name: 'leftIconClassName',
    type: 'string',
    ru: 'Класс левой иконки.',
    en: 'Class of the left icon.',
  },
  {
    name: 'rightIconClassName',
    type: 'string',
    ru: 'Класс правой иконки.',
    en: 'Class of the right icon.',
  },
];
const change: ComponentProp = {
  name: 'onChange',
  type: 'function',
  ru: 'Вызывается после изменения значения.',
  en: 'Called when the value changes.',
};
const changeChecked: ComponentProp = {
  ...change,
  type: '(checked: boolean, value: string, event: InputEvent) => void',
  ru: 'Сообщает новое состояние и значение пункта.',
  en: 'Reports the new checked state and item value.',
};
const changeValues: ComponentProp = {
  ...change,
  type: '(values: string[]) => void',
  ru: 'Сообщает массив выбранных значений.',
  en: 'Reports the selected values.',
};
const changeText: ComponentProp = {
  ...change,
  type: '(value: string, event: InputEvent) => void',
  ru: 'Сообщает новую строку и событие ввода.',
  en: 'Reports the new text and input event.',
};
const value: ComponentProp = {
  name: 'value',
  type: 'string',
  ru: 'Текущее значение управляемого компонента.',
  en: 'Current value of a controlled component.',
};
const defaultValue: ComponentProp = {
  name: 'defaultValue',
  type: 'string | string[]',
  ru: 'Начальное значение без внешнего управления.',
  en: 'Initial value when uncontrolled.',
};
const placeholder: ComponentProp = {
  name: 'placeholder',
  type: 'string',
  ru: 'Подсказка в пустом поле.',
  en: 'Hint in an empty field.',
  initial: 'Placeholder',
  control: 'text',
};
const inputProps: ComponentProp[] = [
  sizeSM,
  disabled,
  error,
  placeholder,
  value,
  changeText,
  className,
  wrapperClassName,
];
const linkProps: ComponentProp[] = [
  {
    name: 'href',
    type: 'string',
    ru: 'Рендерит ссылку вместо кнопки.',
    en: 'Renders a link instead of a button.',
    initial: '',
    control: 'text',
  },
  {
    name: 'linkComponent',
    type: 'ElementType',
    ru: 'Компонент ссылки, например Next.js Link.',
    en: 'Custom link component, such as Next.js Link.',
  },
  {
    name: 'target',
    type: "'_self' | '_blank'",
    ru: 'Где открыть ссылку.',
    en: 'Where to open the link.',
    default: '_self',
    options: ['_self', '_blank'],
    control: 'select',
  },
  {
    name: 'type',
    type: "'button' | 'reset' | 'submit'",
    ru: 'Тип HTML-кнопки.',
    en: 'HTML button type.',
    default: 'button',
    options: ['button', 'reset', 'submit'],
    control: 'select',
  },
];

export const componentReference: Record<string, ComponentReference> = {
  Button: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Button' },
      sizeAll,
      {
        name: 'theme',
        type: "'filled' | 'light' | 'border' | 'ghost'",
        ru: 'Оформление кнопки.',
        en: 'Button appearance.',
        default: 'filled',
        options: ['filled', 'light', 'border', 'ghost'],
        control: 'select',
      },
      color,
      disabled,
      loading,
      leftIcon,
      rightIcon,
      ...iconClasses,
      { name: 'onClick', type: '(event) => void', ru: 'Обработчик нажатия.', en: 'Click handler.' },
      ...linkProps,
      className,
      textClassName,
    ],
  },
  ButtonGroup: {
    props: [
      {
        ...children,
        type: 'Button[] | Dropdown[]',
        ru: 'Кнопки и меню в одной группе.',
        en: 'Buttons and menus in one group.',
      },
      sizeAll,
      className,
    ],
  },
  Badge: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Badge' },
      sizeSM,
      {
        name: 'theme',
        type: "'filled' | 'light' | 'border'",
        ru: 'Оформление бейджа.',
        en: 'Badge appearance.',
        default: 'filled',
        options: ['filled', 'light', 'border'],
        control: 'select',
      },
      color,
      leftIcon,
      rightIcon,
      ...iconClasses,
      className,
      textClassName,
    ],
  },
  Tag: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Tag' },
      sizeSM,
      {
        name: 'theme',
        type: "'light' | 'border'",
        ru: 'Оформление тега.',
        en: 'Tag appearance.',
        default: 'light',
        options: ['light', 'border'],
        control: 'select',
      },
      checked,
      disabled,
      loading,
      leftIcon,
      rightIcon,
      ...iconClasses,
      {
        name: 'onClick',
        type: '(event) => void',
        ru: 'Обработчик выбора тега.',
        en: 'Tag selection handler.',
      },
      ...linkProps,
      className,
      textClassName,
    ],
  },
  Checkbox: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Label' },
      sizeSM,
      labelPlace,
      checked,
      disabled,
      {
        name: 'indeterminate',
        type: 'boolean',
        ru: 'Промежуточное состояние, например при частичном выборе.',
        en: 'Mixed state, for example when some items are selected.',
        default: false,
        control: 'boolean',
      },
      { ...value, ru: 'Значение пункта формы.', en: 'Form item value.' },
      changeChecked,
      className,
      wrapperClassName,
      textClassName,
    ],
  },
  CheckboxGroup: {
    props: [
      {
        ...children,
        type: 'Checkbox[] | Switch[]',
        ru: 'Пункты группы; можно сочетать Checkbox и Switch.',
        en: 'Group items; Checkbox and Switch can be combined.',
      },
      {
        name: 'itemType',
        type: "'Checkbox' | 'Switch'",
        ru: 'Тип элементов в демонстрации.',
        en: 'Item type in this demo.',
        initial: 'Checkbox',
        options: ['Checkbox', 'Switch'],
        control: 'select',
        demoOnly: true,
      },
      { ...sizeSM, default: undefined, initial: 'm' },
      disabled,
      { ...value, type: 'string[]', ru: 'Выбранные значения.', en: 'Selected values.' },
      { ...defaultValue, type: 'string[]', default: '[]' },
      changeValues,
      className,
    ],
  },
  Switch: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Label' },
      sizeSM,
      labelPlace,
      checked,
      disabled,
      { ...value, ru: 'Значение пункта формы.', en: 'Form item value.' },
      changeChecked,
      className,
      wrapperClassName,
      textClassName,
    ],
  },
  Radio: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Label' },
      sizeSM,
      labelPlace,
      checked,
      disabled,
      { ...value, ru: 'Значение варианта выбора.', en: 'Choice value.' },
      {
        name: 'name',
        type: 'string',
        ru: 'Имя нативной radio-группы.',
        en: 'Native radio group name.',
      },
      changeChecked,
      className,
      wrapperClassName,
      textClassName,
    ],
  },
  RadioGroup: {
    props: [
      { ...children, type: 'Radio[]', ru: 'Варианты выбора.', en: 'Radio choices.' },
      { ...sizeSM, default: undefined, initial: 'm' },
      disabled,
      { ...value, ru: 'Выбранное значение.', en: 'Selected value.' },
      defaultValue,
      changeChecked,
      className,
    ],
  },
  InlineRadio: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Label' },
      sizeSM,
      checked,
      disabled,
      { ...value, ru: 'Значение варианта выбора.', en: 'Choice value.' },
      changeChecked,
      className,
      textClassName,
    ],
  },
  InlineRadioGroup: {
    props: [
      {
        ...children,
        type: 'InlineRadio[]',
        ru: 'Варианты в одной строке.',
        en: 'Choices in one row.',
      },
      { ...sizeSM, default: undefined, initial: 'm' },
      disabled,
      { ...value, ru: 'Выбранное значение.', en: 'Selected value.' },
      defaultValue,
      changeChecked,
      className,
    ],
  },
  Input: {
    parts: ['Control', 'LeftAddon', 'RightAddon'],
    props: [
      ...inputProps.map((prop) =>
        ['value', 'onChange', 'placeholder'].includes(prop.name)
          ? { ...prop, part: 'Control' }
          : prop
      ),
      {
        name: 'type',
        type: 'HTML input type',
        ru: 'Тип поля: text, email, password и другие нативные типы.',
        en: 'Input type: text, email, password and other native types.',
        default: 'text',
        options: [
          'text',
          'number',
          'email',
          'password',
          'url',
          'tel',
          'search',
          'date',
          'datetime-local',
          'month',
          'week',
          'time',
        ],
        control: 'select',
        part: 'Control',
      },
      { ...leftIcon, part: 'Control' },
      { ...rightIcon, part: 'Control' },
      ...iconClasses.map((prop) => ({ ...prop, part: 'Control' })),
      { ...textClassName, part: 'Control' },
      {
        name: 'addon',
        type: 'ReactNode',
        ru: 'Дополнение через Input.LeftAddon или Input.RightAddon.',
        en: 'Extra content via Input.LeftAddon or Input.RightAddon.',
        options: ['none', 'left', 'right'],
        control: 'select',
        initial: 'none',
        demoOnly: true,
      },
    ],
  },
  Textarea: {
    props: [
      ...inputProps,
      {
        name: 'rows',
        type: 'number',
        ru: 'Число строк видимой области.',
        en: 'Number of visible rows.',
      },
    ],
  },
  Select: {
    props: [
      ...inputProps.filter((prop) => prop.name !== 'value' && prop.name !== 'onChange'),
      {
        ...value,
        type: 'Option | Option[]',
        ru: 'Текущий выбранный вариант.',
        en: 'Currently selected choice.',
      },
      { ...change, type: '(value: Option | Option[]) => void' },
      {
        ...defaultValue,
        type: 'Option | Option[]',
        ru: 'Начальный выбранный вариант.',
        en: 'Initially selected choice.',
      },
      {
        name: 'options',
        type: 'Option[]',
        ru: 'Варианты с display, value и необязательным disabled или badge.',
        en: 'Choices with display, value and optional disabled or badge.',
      },
      {
        name: 'multiple',
        type: 'boolean',
        ru: 'Разрешает несколько значений.',
        en: 'Allows multiple values.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'search',
        type: 'boolean',
        ru: 'Добавляет поиск по вариантам.',
        en: 'Adds filtering of choices.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'searchPlaceholder',
        type: 'string',
        ru: 'Подсказка в строке поиска.',
        en: 'Search field hint.',
      },
      {
        name: 'dropdownClassName',
        type: 'string',
        ru: 'Класс списка вариантов.',
        en: 'Class of the options list.',
      },
      {
        name: 'dropdownItemClassName',
        type: 'string',
        ru: 'Класс пункта списка.',
        en: 'Class of an option.',
      },
    ],
  },
  Search: {
    props: [
      ...inputProps.filter((prop) => prop.name !== 'value' && prop.name !== 'onChange'),
      {
        ...value,
        type: 'Option | Option[]',
        ru: 'Текущий выбранный вариант.',
        en: 'Currently selected choice.',
      },
      { ...change, type: '(value: Option | Option[]) => void' },
      {
        ...defaultValue,
        type: 'Option | Option[]',
        ru: 'Начальный выбранный вариант.',
        en: 'Initially selected choice.',
      },
      {
        name: 'options',
        type: 'Option[]',
        ru: 'Список вариантов для поиска.',
        en: 'List of searchable choices.',
      },
      {
        name: 'multiple',
        type: 'boolean',
        ru: 'Разрешает несколько значений.',
        en: 'Allows multiple values.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'dropdownClassName',
        type: 'string',
        ru: 'Класс списка вариантов.',
        en: 'Class of the options list.',
      },
      {
        name: 'dropdownItemClassName',
        type: 'string',
        ru: 'Класс пункта списка.',
        en: 'Class of an option.',
      },
    ],
  },
  Field: {
    parts: ['Label', 'Control', 'Description'],
    props: [
      {
        ...children,
        ru: 'Составные части поля: подпись, контрол и подсказка.',
        en: 'Field parts: label, control and description.',
      },
      error,
      {
        name: 'control',
        type: 'ReactNode',
        ru: 'Любой контрол внутри Field.Control.',
        en: 'Any control inside Field.Control.',
        options: ['Input', 'Textarea', 'Select', 'Search'],
        control: 'select',
        initial: 'Input',
        demoOnly: true,
      },
      {
        name: 'label',
        type: 'string',
        ru: 'Текст Field.Label в примере.',
        en: 'Field.Label text in the example.',
        initial: 'Label',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'description',
        type: 'string',
        ru: 'Текст Field.Description в примере.',
        en: 'Field.Description text in the example.',
        initial: 'Description',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'htmlFor',
        type: 'string',
        ru: 'Связывает подпись с полем по id.',
        en: 'Associates the label with the input id.',
      },
      disabled,
      className,
    ],
  },
  Dropdown: {
    parts: ['Trigger', 'Content', 'Item'],
    props: [
      { ...children, ru: 'Кнопка открытия и содержимое меню.', en: 'Trigger and menu content.' },
      {
        name: 'align',
        type: "'left' | 'right'",
        ru: 'Выравнивание меню относительно кнопки.',
        en: 'Menu alignment relative to the trigger.',
        default: 'left',
        options: ['left', 'right'],
        control: 'select',
        part: 'Content',
      },
      className,
      wrapperClassName,
    ],
  },
  DropdownItem: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Dropdown Item' },
      disabled,
      {
        name: 'borderTop',
        type: 'boolean',
        ru: 'Разделитель над пунктом.',
        en: 'Divider above the item.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'borderBottom',
        type: 'boolean',
        ru: 'Разделитель под пунктом.',
        en: 'Divider below the item.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'badge',
        type: 'Badge',
        ru: 'Бейдж справа от подписи.',
        en: 'Badge to the right of the label.',
        initial: false,
        control: 'boolean',
      },
      leftIcon,
      rightIcon,
      ...iconClasses,
      {
        name: 'onClick',
        type: '(event) => void',
        ru: 'Обработчик выбора пункта.',
        en: 'Item click handler.',
      },
      ...linkProps,
      className,
      wrapperClassName,
      textClassName,
    ],
  },
  Tabs: {
    props: [
      {
        ...children,
        type: 'Tab[]',
        ru: 'Вкладки с label и содержимым.',
        en: 'Tabs with labels and content.',
      },
      {
        name: 'defaultIndex',
        type: 'number',
        ru: 'Индекс начальной активной вкладки.',
        en: 'Initial active tab index.',
        default: 0,
        options: ['0', '1', '2', '3', '4'],
        control: 'select',
      },
      {
        name: 'onChange',
        type: '(index, event) => void',
        ru: 'Вызывается при выборе вкладки.',
        en: 'Called when the active tab changes.',
      },
      className,
    ],
  },
  Tab: {
    props: [
      {
        name: 'label',
        type: 'string',
        ru: 'Текст вкладки.',
        en: 'Tab label.',
        initial: 'Tab',
        control: 'text',
      },
      {
        name: 'active',
        type: 'boolean',
        ru: 'Активное состояние отдельно стоящей вкладки.',
        en: 'Active state of a standalone tab.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'indicator',
        type: 'boolean',
        ru: 'Линия под активной вкладкой.',
        en: 'Line below the active tab.',
        default: true,
        control: 'boolean',
      },
      disabled,
      leftIcon,
      rightIcon,
      ...iconClasses,
      {
        name: 'onClick',
        type: '(event) => void',
        ru: 'Обработчик нажатия на вкладку.',
        en: 'Tab click handler.',
      },
      ...linkProps,
      className,
      textClassName,
    ],
  },
  Collapse: {
    props: [
      {
        name: 'summary',
        type: 'string',
        ru: 'Заголовок раскрываемого блока.',
        en: 'Expandable section heading.',
        initial: 'Summary',
        control: 'text',
      },
      { ...children, ru: 'Содержимое раскрытого блока.', en: 'Content of the expanded section.' },
      {
        name: 'open',
        type: 'boolean',
        ru: 'Управляемое состояние открытия.',
        en: 'Controlled open state.',
        initial: false,
        control: 'boolean',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        ru: 'Начальное состояние без внешнего управления.',
        en: 'Initial open state when uncontrolled.',
        default: false,
      },
      {
        name: 'onToggle',
        type: '(event) => void',
        ru: 'Событие изменения состояния элемента details.',
        en: 'Fires when the details element changes state.',
      },
      {
        name: 'contentClassName',
        type: 'string',
        ru: 'Класс содержимого раскрытого блока.',
        en: 'Class of the expanded content.',
      },
      className,
    ],
  },
  CollapseGroup: {
    props: [
      {
        ...children,
        type: 'Collapse[]',
        ru: 'Раскрываемые секции группы.',
        en: 'Expandable sections in the group.',
      },
      {
        name: 'joined',
        type: 'boolean',
        ru: 'Объединяет секции в один блок.',
        en: 'Joins sections into one block.',
        default: false,
        control: 'boolean',
      },
      { name: 'name', type: 'string', ru: 'Общее имя секций.', en: 'Shared section name.' },
      className,
    ],
  },
  Alert: {
    parts: ['Title', 'Description', 'Actions'],
    props: [
      {
        ...children,
        ru: 'Заголовок, описание и необязательные действия.',
        en: 'Title, description and optional actions.',
      },
      color,
      {
        name: 'title',
        type: 'string',
        ru: 'Текст Alert.Title в примере.',
        en: 'Alert.Title text in the demo.',
        initial: 'Headline',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'description',
        type: 'string',
        ru: 'Текст Alert.Description в примере.',
        en: 'Alert.Description text in the demo.',
        initial: 'Description',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'actions',
        type: 'boolean',
        ru: 'Показывает Alert.Actions в примере.',
        en: 'Shows Alert.Actions in the demo.',
        initial: false,
        control: 'boolean',
        demoOnly: true,
      },
      {
        name: 'open',
        type: 'boolean',
        ru: 'Управляемая видимость.',
        en: 'Controlled visibility.',
        initial: true,
        control: 'boolean',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        ru: 'Начальная видимость без внешнего управления.',
        en: 'Initial visibility when uncontrolled.',
        default: true,
      },
      {
        name: 'onOpenChange',
        type: '(open) => void',
        ru: 'Вызывается при закрытии.',
        en: 'Called when the alert closes.',
      },
      {
        name: 'closeButtonAriaLabel',
        type: 'string',
        ru: 'Доступное имя кнопки закрытия.',
        en: 'Accessible name of the close button.',
        default: 'Close alert',
      },
      {
        name: 'as',
        type: "'h1' … 'h6'",
        ru: 'Уровень заголовка Alert.Title.',
        en: 'Heading level of Alert.Title.',
        default: 'h3',
        options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
        control: 'select',
        part: 'Title',
      },
      className,
    ],
  },
  Dialog: {
    parts: ['Trigger', 'Content', 'Header', 'Body', 'Footer', 'Close'],
    props: [
      {
        name: 'id',
        type: 'string',
        ru: 'Уникальный идентификатор диалога.',
        en: 'Unique dialog identifier.',
      },
      {
        name: 'open',
        type: 'boolean',
        ru: 'Управляемая видимость диалога.',
        en: 'Controlled dialog visibility.',
        initial: false,
        control: 'boolean',
      },
      {
        name: 'backdrop',
        type: 'boolean',
        ru: 'Затемнение за диалогом.',
        en: 'Backdrop behind the dialog.',
        default: true,
        control: 'boolean',
      },
      {
        name: 'animationDuration',
        type: 'number',
        ru: 'Длительность анимации в миллисекундах.',
        en: 'Animation duration in milliseconds.',
        default: 200,
        control: 'number',
      },
      {
        name: 'header',
        type: 'string',
        ru: 'Текст Dialog.Header в примере.',
        en: 'Dialog.Header text in the demo.',
        initial: 'Dialog title',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'body',
        type: 'string',
        ru: 'Текст Dialog.Body в примере.',
        en: 'Dialog.Body text in the demo.',
        initial: 'Dialog content',
        control: 'text',
        demoOnly: true,
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        ru: 'Начальная видимость без внешнего управления.',
        en: 'Initial visibility when uncontrolled.',
        default: false,
      },
      {
        name: 'onOpenChange',
        type: '(open: boolean, id?: string) => void',
        ru: 'Вызывается при изменении видимости.',
        en: 'Called when visibility changes.',
      },
      {
        name: 'onClose',
        type: '(open: boolean, id?: string) => void',
        ru: 'Вызывается после закрытия.',
        en: 'Called after closing.',
      },
      children,
      className,
    ],
  },
  DialogProvider: {
    props: [
      {
        ...children,
        ru: 'Дочерние компоненты с доступом к useDialog и useShowDialog.',
        en: 'Descendants that can use useDialog and useShowDialog.',
      },
      {
        name: 'animationDuration',
        type: 'number',
        ru: 'Длительность анимации диалога в миллисекундах.',
        en: 'Dialog animation duration in milliseconds.',
        initial: 200,
        control: 'number',
      },
      className,
    ],
  },
  Notification: {
    props: [
      {
        name: 'headline',
        type: 'string',
        ru: 'Заголовок уведомления.',
        en: 'Notification heading.',
        initial: 'Saved',
        control: 'text',
      },
      {
        ...children,
        type: 'string',
        ru: 'Текст уведомления.',
        en: 'Notification message.',
        initial: 'Changes saved.',
        control: 'text',
      },
      {
        name: 'icon',
        type: 'SvgType',
        ru: 'Иконка уведомления.',
        en: 'Notification icon.',
        initial: 'none',
        options: ['none', 'check', 'search', 'user'],
        control: 'select',
      },
      {
        name: 'iconClassName',
        type: 'string',
        ru: 'Класс иконки уведомления.',
        en: 'Class of the notification icon.',
      },
      {
        name: 'open',
        type: 'boolean',
        ru: 'Управляемая видимость уведомления.',
        en: 'Controlled notification visibility.',
        initial: false,
        control: 'boolean',
      },
      {
        name: 'defaultOpen',
        type: 'boolean',
        ru: 'Начальная видимость без внешнего управления.',
        en: 'Initial visibility when uncontrolled.',
        default: false,
      },
      {
        name: 'top',
        type: 'number',
        ru: 'Отступ уведомления сверху в пикселях.',
        en: 'Top offset of the notification in pixels.',
        default: 0,
        initial: 80,
        control: 'number',
      },
      {
        name: 'delay',
        type: 'number',
        ru: 'Время до автоматического закрытия в миллисекундах.',
        en: 'Time before auto-dismiss in milliseconds.',
        default: 5000,
        control: 'number',
      },
      {
        name: 'disableTimer',
        type: 'boolean',
        ru: 'Отключает автоматическое закрытие.',
        en: 'Disables auto-dismiss.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableProgressBar',
        type: 'boolean',
        ru: 'Скрывает индикатор времени.',
        en: 'Hides the timer progress bar.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableTimerPauseOnHover',
        type: 'boolean',
        ru: 'Таймер не останавливается при наведении.',
        en: 'Timer does not pause on hover.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableCloseByClickInsideAnywhere',
        type: 'boolean',
        ru: 'Запрещает закрывать нажатием внутри уведомления.',
        en: 'Prevents dismissing by clicking inside.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'animationDuration',
        type: 'number',
        ru: 'Длительность анимации в миллисекундах.',
        en: 'Animation duration in milliseconds.',
        default: 200,
        control: 'number',
      },
      {
        name: 'isMouseInside',
        type: 'boolean',
        ru: 'Внешнее управление состоянием наведения.',
        en: 'External control of hover state.',
      },
      {
        name: 'closeButtonAriaLabel',
        type: 'string',
        ru: 'Доступное имя кнопки закрытия.',
        en: 'Accessible name of the close button.',
        default: 'Close notification',
      },
      {
        name: 'onClick',
        type: '() => void',
        ru: 'Обработчик нажатия внутри уведомления.',
        en: 'Click handler inside the notification.',
      },
      {
        name: 'onOpenChange',
        type: '(open, id?) => void',
        ru: 'Вызывается при изменении видимости.',
        en: 'Called when visibility changes.',
      },
      {
        name: 'onClose',
        type: '(open: boolean, id?: string) => void',
        ru: 'Вызывается после закрытия.',
        en: 'Called after closing.',
      },
      {
        name: 'id',
        type: 'string',
        ru: 'Идентификатор уведомления.',
        en: 'Notification identifier.',
      },
      className,
    ],
  },
  NotificationsProvider: {
    props: [
      {
        ...children,
        ru: 'Дочерние компоненты с доступом к useNotifications.',
        en: 'Descendants that can use useNotifications.',
      },
      {
        name: 'top',
        type: 'number',
        ru: 'Отступ уведомлений сверху в пикселях.',
        en: 'Top offset of notifications in pixels.',
        default: 0,
        initial: 80,
        control: 'number',
      },
      {
        name: 'delay',
        type: 'number',
        ru: 'Время показа уведомления в миллисекундах.',
        en: 'Notification lifetime in milliseconds.',
        default: 5000,
        control: 'number',
      },
      {
        name: 'animationDuration',
        type: 'number',
        ru: 'Длительность анимации в миллисекундах.',
        en: 'Animation duration in milliseconds.',
        default: 200,
        control: 'number',
      },
      {
        name: 'estimatedNotificationHeight',
        type: 'number',
        ru: 'Оценка высоты для раскладки уведомлений.',
        en: 'Estimated height for notification layout.',
        default: 80,
        control: 'number',
      },
      {
        name: 'disableTimer',
        type: 'boolean',
        ru: 'Отключает автоматическое закрытие.',
        en: 'Disables auto-dismiss.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableProgressBar',
        type: 'boolean',
        ru: 'Скрывает индикатор времени.',
        en: 'Hides the timer progress bar.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableTimerPauseOnHover',
        type: 'boolean',
        ru: 'Таймер не останавливается при наведении.',
        en: 'Timer does not pause on hover.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableTimerPauseOnContainerHover',
        type: 'boolean',
        ru: 'Таймер не останавливается при наведении на контейнер.',
        en: 'Timer does not pause when hovering the container.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'disableCloseByClickInsideAnywhere',
        type: 'boolean',
        ru: 'Запрещает закрывать нажатием внутри.',
        en: 'Prevents dismissing by clicking inside.',
        default: false,
        control: 'boolean',
      },
      className,
    ],
  },
  PBCProvider: {
    props: [
      { ...children, ru: 'Дочернее дерево приложения.', en: 'Application children.' },
      {
        name: 'dialogDuration',
        type: 'number',
        ru: 'Время анимации диалога в примере.',
        en: 'Dialog animation duration in the demo.',
        initial: 200,
        control: 'number',
        demoOnly: true,
      },
      {
        name: 'notificationTop',
        type: 'number',
        ru: 'Отступ уведомлений в примере.',
        en: 'Notification offset in the demo.',
        initial: 20,
        control: 'number',
        demoOnly: true,
      },
      {
        name: 'dialog',
        type: 'DialogProviderProps',
        ru: 'Настройки DialogProvider, например animationDuration.',
        en: 'DialogProvider settings such as animationDuration.',
      },
      {
        name: 'notifications',
        type: 'NotificationsProviderProps',
        ru: 'Настройки NotificationsProvider: top, delay, анимация и таймер.',
        en: 'NotificationsProvider settings: top, delay, animation and timer.',
      },
    ],
  },
  Headline: {
    props: [
      {
        name: 'as',
        type: "'h1' … 'h6'",
        ru: 'Уровень HTML-заголовка.',
        en: 'HTML heading level.',
        default: 'h1',
        options: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6'],
        control: 'select',
      },
      { ...children, type: 'string', control: 'text', initial: 'Headline' },
      className,
    ],
  },
  Container: {
    parts: ['LeftAside', 'Main', 'RightAside'],
    props: [
      {
        name: 'size',
        type: "'full' | 'm' | 's'",
        ru: 'Максимальная ширина контейнера.',
        en: 'Maximum container width.',
        default: 'full',
        options: ['full', 'm', 's'],
        control: 'select',
      },
      {
        name: 'leftAside',
        type: 'ReactNode',
        ru: 'Левая колонка через Container.LeftAside.',
        en: 'Left column via Container.LeftAside.',
        initial: true,
        control: 'boolean',
        demoOnly: true,
      },
      {
        name: 'rightAside',
        type: 'ReactNode',
        ru: 'Правая колонка через Container.RightAside.',
        en: 'Right column via Container.RightAside.',
        initial: true,
        control: 'boolean',
        demoOnly: true,
      },
      {
        ...children,
        ru: 'Составные части LeftAside, Main и RightAside.',
        en: 'Compound parts LeftAside, Main and RightAside.',
      },
      className,
      wrapperClassName,
    ],
  },
  Text: {
    props: [
      sizeSML,
      {
        name: 'medium',
        type: 'boolean',
        ru: 'Увеличенная насыщенность шрифта.',
        en: 'Medium font weight.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'as',
        type: 'ElementType',
        ru: 'HTML-тег текста.',
        en: 'HTML text element.',
        default: 'span',
        options: ['span', 'p', 'div'],
        control: 'select',
      },
      { ...children, type: 'string', control: 'text', initial: 'Label' },
      className,
    ],
  },
  Icon: {
    props: [
      {
        name: 'tag',
        type: 'SvgType',
        ru: 'SVG-компонент иконки.',
        en: 'SVG icon component.',
        initial: 'check',
        options: ['check', 'search', 'user'],
        control: 'select',
      },
      sizeSML,
      className,
    ],
  },
  Content: {
    props: [
      { ...children, type: 'string', control: 'text', initial: 'Content' },
      sizeSML,
      {
        name: 'medium',
        type: 'boolean',
        ru: 'Увеличенная насыщенность текста.',
        en: 'Medium text weight.',
        default: false,
        control: 'boolean',
      },
      {
        name: 'as',
        type: 'ElementType',
        ru: 'HTML-тег обёртки.',
        en: 'HTML wrapper element.',
        default: 'span',
        options: ['div', 'span'],
        control: 'select',
      },
      leftIcon,
      rightIcon,
      ...iconClasses,
      className,
      textClassName,
    ],
  },
  useClickOutside: {
    kind: 'hook',
    props: [
      {
        name: 'refs',
        type: 'RefObject<T | null>[]',
        ru: 'Элементы, внутри которых нажатие не вызывает callback.',
        en: 'Elements whose inside clicks do not trigger the callback.',
      },
      {
        name: 'callback',
        type: '(event?: MouseEvent | TouchEvent) => void',
        ru: 'Вызывается при нажатии вне всех переданных элементов.',
        en: 'Runs on a click or touch outside every provided element.',
      },
    ],
    returns: [
      { name: 'result', type: 'void', ru: 'Ничего не возвращает.', en: 'Returns nothing.' },
    ],
  },
  useControllableState: {
    kind: 'hook',
    props: [
      {
        name: 'value?',
        type: 'T',
        ru: 'Внешнее значение для управляемого состояния. Укажите его или defaultValue.',
        en: 'External value for controlled state. Provide this or defaultValue.',
      },
      {
        name: 'defaultValue?',
        type: 'T',
        ru: 'Начальное внутреннее значение. Укажите его или value.',
        en: 'Initial internal value. Provide this or value.',
      },
      {
        name: 'onChange?',
        type: '(value: T) => void',
        ru: 'Вызывается при изменении значения.',
        en: 'Called when the value changes.',
      },
    ],
    returns: [
      {
        name: '[0] value',
        type: 'T | undefined',
        ru: 'Текущее значение. undefined возможно, если не переданы value и defaultValue.',
        en: 'Current value. Can be undefined when neither value nor defaultValue is provided.',
      },
      {
        name: '[1] setValue',
        type: '(value: T) => void',
        ru: 'Устанавливает значение или сообщает об изменении через onChange.',
        en: 'Sets the value or reports a change through onChange.',
      },
    ],
  },
  useCountdown: {
    kind: 'hook',
    props: [
      {
        name: 'delay',
        type: 'number',
        ru: 'Длительность таймера в миллисекундах.',
        en: 'Timer duration in milliseconds.',
      },
      { name: 'paused', type: 'boolean', ru: 'Приостанавливает таймер.', en: 'Pauses the timer.' },
      {
        name: 'onComplete?',
        type: '() => void',
        ru: 'Вызывается по окончании отсчёта.',
        en: 'Called when the countdown finishes.',
      },
      { name: 'enabled?', type: 'boolean', ru: 'Включает отсчёт.', en: 'Enables the countdown.' },
    ],
    returns: [
      {
        name: 'progress',
        type: 'number',
        ru: 'Прогресс от 0 до 100.',
        en: 'Progress from 0 to 100.',
      },
    ],
  },
  useDialog: {
    kind: 'hook',
    props: [],
    returns: [
      {
        name: 'dialogs',
        type: 'DialogRecord[]',
        ru: 'Зарегистрированные диалоги.',
        en: 'Registered dialogs.',
      },
      {
        name: 'activeDialog',
        type: 'DialogRecord | null',
        ru: 'Активный диалог или null.',
        en: 'Active dialog or null.',
      },
      {
        name: 'closeDialog',
        type: '(id?: string) => void',
        ru: 'Закрывает диалог по id или активный диалог, если id не передан.',
        en: 'Closes a dialog by id or the active dialog when no id is given.',
      },
    ],
  },
  useHoverControllable: {
    kind: 'hook',
    props: [
      {
        name: 'ref?',
        type: 'RefObject<T | null>',
        ru: 'Существующий ref элемента, за которым нужно следить.',
        en: 'Existing ref for the element to observe.',
      },
      {
        name: 'value?',
        type: 'boolean',
        ru: 'Внешнее состояние наведения.',
        en: 'External hover state.',
      },
      {
        name: 'defaultValue?',
        type: 'boolean',
        ru: 'Начальное внутреннее состояние.',
        en: 'Initial internal state.',
      },
      {
        name: 'onChange?',
        type: '(value: boolean) => void',
        ru: 'Вызывается при изменении состояния наведения.',
        en: 'Called when the hover state changes.',
      },
      {
        name: 'enabled?',
        type: 'boolean',
        ru: 'Включает отслеживание наведения.',
        en: 'Enables hover tracking.',
      },
    ],
    returns: [
      {
        name: '[0] hovered',
        type: 'boolean',
        ru: 'Текущее состояние наведения.',
        en: 'Current hover state.',
      },
      {
        name: '[1] setHovered',
        type: '(value: boolean) => void',
        ru: 'Меняет состояние наведения.',
        en: 'Changes the hover state.',
      },
      {
        name: '[2] hoverRef',
        type: '(node: T | null) => void',
        ru: 'Callback ref для отслеживаемого элемента.',
        en: 'Callback ref for the observed element.',
      },
    ],
  },
  useKeydown: {
    kind: 'hook',
    props: [
      {
        name: 'keys',
        type: 'string[]',
        ru: 'Клавиши, на которые реагирует хук.',
        en: 'Keys the hook listens for.',
      },
      {
        name: 'callback',
        type: '(event: KeyboardEvent) => void',
        ru: 'Вызывается при нажатии указанной клавиши.',
        en: 'Called when a specified key is pressed.',
      },
      {
        name: 'shouldHandleWhenDefaultPrevented?',
        type: 'boolean',
        ru: 'Разрешает обработку события с preventDefault().',
        en: 'Allows handling events with preventDefault() called.',
      },
    ],
    returns: [
      { name: 'result', type: 'void', ru: 'Ничего не возвращает.', en: 'Returns nothing.' },
    ],
  },
  useMergeRefs: {
    kind: 'hook',
    props: [
      {
        name: '...refs',
        type: '(Ref<T> | undefined)[]',
        ru: 'Объектные и callback ref, которые нужно объединить.',
        en: 'Object and callback refs to combine.',
      },
    ],
    returns: [
      {
        name: 'ref',
        type: 'RefCallback<T>',
        ru: 'Общий callback ref для элемента.',
        en: 'Combined callback ref for the element.',
      },
    ],
  },
  useNotifications: {
    kind: 'hook',
    props: [],
    returns: [
      {
        name: 'notifications',
        type: 'NotificationRecord[]',
        ru: 'Текущие уведомления.',
        en: 'Current notifications.',
      },
      {
        name: 'showNotification',
        type: '(value: NotificationInput) => string',
        ru: 'Показывает уведомление и возвращает его id.',
        en: 'Shows a notification and returns its id.',
      },
      {
        name: 'hideNotification',
        type: '(id: string) => void',
        ru: 'Скрывает уведомление по id.',
        en: 'Hides a notification by id.',
      },
    ],
  },
  useScreenSize: {
    kind: 'hook',
    props: [],
    returns: [
      {
        name: 'width',
        type: 'number',
        ru: 'Ширина окна в пикселях.',
        en: 'Window width in pixels.',
      },
      {
        name: 'height',
        type: 'number',
        ru: 'Высота окна в пикселях.',
        en: 'Window height in pixels.',
      },
    ],
  },
  useShowDialog: {
    kind: 'hook',
    props: [
      {
        name: 'dialog',
        type: '() => ReactElement<DialogProps>',
        ru: 'Функция, создающая диалог.',
        en: 'Function that creates the dialog.',
      },
      {
        name: 'dependencies?',
        type: 'readonly unknown[]',
        ru: 'Зависимости функции создания диалога.',
        en: 'Dependencies of the dialog factory.',
      },
    ],
    returns: [
      {
        name: 'openDialog',
        type: '() => string',
        ru: 'Открывает диалог и возвращает его id.',
        en: 'Opens the dialog and returns its id.',
      },
    ],
  },
};
